####################################################################
#                        Database Settings                         #
####################################################################

user: postgres
dbname: bot
password: 542919
host: 0.0.0.0
port: 5432

