####################################################################
#                        Database Settings                         #
####################################################################

user: discord_user
dbname: bot
host: 127.0.0.1
port: 5432
