####################################################################
#                        Database Settings                         #
####################################################################

user: postgres 
dbname: Fuelbot
password: abc
host: localhost
port: 5432
